### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Droppix** [mjancarik/merkur#133]
Hi,

I try use merkur with nodejs v18.x, I have an error:
> cross-env NODE_CONFIG_DIR='./server/config' NODE_ENV=development nodemon server/server.js --config nodemon.json

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server/**/* build/**/*
[nodemon] watching extensions: cjs,ejs,json,mjs,js,jsx
[nodemon] starting `node server/server.js`
node:internal/modules/cjs/loader:489
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/' is not defined by "exports" in  ..../node_modules/@merkur/integration/package.json

---------------
In the module widgetAPI.js:
**const { createAssets, memo } = require('@merkur/integration/server/')**
It should be replaced by (remove backslash)
**const { createAssets, memo } = require('@merkur/integration/server')**

Thanks

**Comment by mjancarik** [comment]
Hi,

thanks for reporting issue.
